// Autogenerated by "kodi-dev-kit/tools/code-generator/code_generator__addon_depends_angle.py"
// Generated: 2026-04-15 20:14:17.214240

#define ANGLE_PROGRAM_VERSION "d9fc4a372074"
#define ANGLE_PROGRAM_VERSION_HASH_SIZE 12
