// Autogenerated by "kodi-dev-kit/tools/code-generator/code_generator__addon_depends_angle.py"
// Generated: 2026-04-15 20:14:17.207028

#define ANGLE_COMMIT_HASH "d9fc4a372074"
#define ANGLE_COMMIT_HASH_SIZE 12
#define ANGLE_COMMIT_DATE "20250818-2310"
#define ANGLE_REVISION 7258
